### ISSUE TITLE
Help with build 

### ISSUE THREAD

**Issue by Macbet** [jkutianski/qmk_compaq_mx-11800#1]
Hi! Thank you very much for this repository!
I'm trying to build the firmware and clone  first your fork repo  https://github.com/jkutianski/qmk_firmware
After i clone this repo in keyboard directory
But when i try to compile with `make qmk_compaq_mx-11800:via` i got errors:
```
QMK Firmware 0.8.164
Making qmk_compaq_mx-11800 with keymap via

avr-gcc (Homebrew AVR GCC 8.4.0) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: keyboards/qmk_compaq_mx-11800/keymaps/via/../../tap_dance.c                             <command-line>: error: ISO C99 requires whitespace after the macro name [-Werror]
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [.build/obj_qmk_compaq_mx-11800_via/../../tap_dance.o] Error 1
make: *** [qmk_compaq_mx-11800:via] Error 1
Make finished with errors
```
Please tell me what I'm doing wrong ?

**Comment by jkutianski** [comment]
Hi @Macbet!
Please, don't use my QMK repo. It's very old.
Try to clone the [QMK](https://github.com/qmk/qmk_firmware) and use the master banch.
Then clone [this repo](https://github.com/jkutianski/qmk_compaq_mx-11800) inside `./qmk_firmware/keyboards/compaq/mx11800`.
After that, go to the root dir of `./qmk_firmware` and execute `make compaq/mx11800:via`

Tell me if works.
